### PR TITLE
feat: add calico support

### PR DESCRIPTION
**Pull request by onedr0p**
### Summary

Adds support for deploying the tigera operator for installing Calico with the following options:

```yaml
calico: false
calico_tigera_manifest: https://docs.projectcalico.org/archive/v3.19/manifests/tigera-operator.yaml
calico_encapsulation: "None"
calico_bgp: false
calico_bgp_peer_ip: null
calico_bgp_as_number: null
calico_bgp_external_ips: null
```

### Issue type

- Feature

### Todo

- Add molecule tests (likely we cannot test BGP but I am very sure it _should_ work)
- Additional checks?

Closes https://github.com/PyratLabs/ansible-role-k3s/issues/121

### CODE REVIEW

**Comment by onedr0p** [comment]
@xanmanning looking for some feedback here, plus I am not sure the best way to set up molecule tests. Thanks!

**Comment by xanmanning** [comment]
Please forgive my ignorance @onedr0p , I don't really use Calico as I don't have a specific need for it yet so your experience is valuable here.

Is there a reason why making use of server manifests would not work? The example I wrote was like this (obvs, not using BGP) https://github.com/PyratLabs/ansible-role-k3s/blob/main/documentation/configuration/use-an-alternate-cni.md

The reason I ask is because I'm trying to keep this as focused on K3S and pulling in Calico sounds like we/I would need to keep on top of the changes in Calico and update the role accordingly? I am unfamiliar with the amount of churn in Calico.

**Comment by onedr0p** [comment]
Calico is very stable and doesn't require much babysitting. The reason I wanted to include this is that if we wanted to add kube-vip (which would be awesome to support a LB out of the box) a CNI must be installed first and Flannel is very basic and doesn't support many features (like BGP).

There seems to be a chick / egg situation where since your role does not deploy a CNI other than flannel it would be impossible to disable it and support deploying kube-vip.

**Comment by onedr0p** [comment]
I don't want this role to turn into kubespray that tries to do everything but adding some community favorites like calico and kube-vip would be very awesome and they are core cluster components.

**Comment by onedr0p** [comment]
Entirely possible using `k3s_server_manifests_templates`

**Pull request closed without merging**
