### PR TITLE
added kubelet args key

### PR DESCRIPTION
**Pull request by carpenike**
I think I got them all, let me know if I missed any.

Signed-off-by: Ryan Holt <ryan@ryanholt.net>

### CODE REVIEW

**Comment by carpenike** [comment]
Closes #12

**Comment by xanmanning** [comment]
Thanks @carpenike - looks like it is covered in terms of how to implement it. I shall test it on my VM cluster.

Any chance an example usage can be put in the README.md somewhere?, eg. under a heading "Important note about `k3s_kubelet_args`" ?

I may adjust the .travis-ci.yml file for testing this before merging this in, hopefully this evening (GMT+0), I'll add it to this branch.

**Comment by carpenike** [comment]
Yup that makes sense. My particular use case is for integration with a a cloud provider. IE: https://itnext.io/how-to-integrate-k3s-with-the-cloud-controller-36bd5020b8f7

**Comment by xanmanning** [comment]
Balls, I did not mean to do that.

**Comment by xanmanning** [comment]
My sincerest apologies @carpenike - I shall recreate this.

**Pull request closed without merging**
