### PR TITLE
Add state-uninstalled

### PR DESCRIPTION
**Pull request by onedr0p**
- Added `state-uninstalled.yml`
- Added `templates/k3s-killall.sh.j2` from k3s repo
- Added `templates/k3s-uninstall.sh.j2` from k3s repo
- Created new `tasks/teardown` directory with uninstall k3s and Docker tasks 

⚠️ A little caution on the uninstall-docker pieces I don't have an environment set up to test all these out.

### CODE REVIEW

**Comment by xanmanning** [comment]
Legend, thanks @onedr0p - seems like you have been reading my mind, or my not-yet-published ToDo list. I shall test this one out, I have a load of VMs with Docker I can try the uninstall on and see what breaks.

**Comment by onedr0p** [comment]
Cool, feel free to ask me to change anything or close this and make changes in a new branch :)

**Comment by xanmanning** [comment]
I may take a while to be able to look at this in detail. Looks like some of the Travis-CI builds have broken due to linting errors, are you able to take a look?

**Comment by onedr0p** [comment]
I'll be able to take a look tonight at those.

**Comment by onedr0p** [comment]
I believe all the issues were fixed, running into API Rate limiting errors now.

**Comment by onedr0p** [comment]
Much thanks with the fixes :)

**Comment by xanmanning** [comment]
Made some slight alterations @onedr0p - Are you happy with these changes? I've tested them on my VMs.

Main change is to remove the steps to uninstall docker prerequisite packages. Main reason for this is that lvm2 is a required package for docker, however it was already installed on my VMs (I was using it) and the uninstall attempted to remove lvm. Oops.

**Comment by onedr0p** [comment]
No worries, I didn't know how far we should go with the uninstalling docker and the deps, or even uninstall docker at all. What you have is fine with me.

**Pull request merged**
