### PR TITLE
Fix check for k3s_token_location

### PR DESCRIPTION
**Pull request by niklasweimann**
### Summary
This PR fixes the check for adding the token to the k3s service file. Bug description in #187
### Issue type
- Bugfix

### CODE REVIEW

**Comment by crutonjohn** [comment]
hmmm...looks like the debian HA is failing because it's trying to download an EPEL package. lol.

**Comment by crutonjohn** [comment]
@xanmanning it looks like we're already in a conditional that is only for `k3s_control_node` [here](https://github.com/PyratLabs/ansible-role-k3s/blob/main/templates/k3s.service.j2#L37). is there any reason for the logic to previously have been `{% if k3s_control_node and not k3s_primary_control_node %}` for the statement in question to begin with?

**Comment by xanmanning** [comment]
> @xanmanning it looks like we're already in a conditional that is only for `k3s_control_node` [here](https://github.com/PyratLabs/ansible-role-k3s/blob/main/templates/k3s.service.j2#L37). is there any reason for the logic to previously have been `{% if k3s_control_node and not k3s_primary_control_node %}` for the statement in question to begin with?

I suspect this will have been a lapse in concentration, this condition probably just needs to be `{% if not k3s_primary_control_node %}`

**Comment by xanmanning** [comment]
> hmmm...looks like the debian HA is failing because it's trying to download an EPEL package. lol.

The HAProxy node in the molecule test is RHEL family (CentOS/RockyLinux)

**Comment by xanmanning** [comment]
Re-running test as the repo might have been down?

**Comment by xanmanning** [comment]
Looks like cluster creation hangs when `k3s_token_location` is undefined.

**Comment by xanmanning** [comment]
@niklasweimann - do you want to give the branch on #190 a go to check it still works?

**Pull request merged**
